### ISSUE TITLE
Error in pydoc from lbits() in ro-ecc/src/conversion.py

### ISSUE THREAD

**Issue by HS-157** [epsi-brest-2016-b3/ro-ecc#2]
I thing name of fonction is *lbin()* and not *bin()*

https://github.com/epsi-brest-2016-b3/ro-ecc/blob/master/src/conversion.py#L52

https://github.com/epsi-brest-2016-b3/ro-ecc/blob/master/src/conversion.py#L56

**Comment by cederhum** [comment]
Thanks, but it cannot be used the way you suppose. Look at the code, lbin is a generator, it cannot be used as a standalone function, the bin function instead is just here to show the binary representation of the figures used one line after. I do confirm bin is here to stay. Thanks anyway!
